using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ArtilleryBullet : MonoBehaviour
{
    public EnemyScriptableObject enemyData;
    public GameObject explosionVFX;

    private CircularIndicator storedData;
    private Collider2D entityCollider;

    private void Start()
    {
        entityCollider = GetComponent<Collider2D>();

    }

    private void Update()
    {
        CheckTrigger();

    }

    void CheckTrigger()
    {
        if (storedData.isInRange == true)
        {
            Debug.Log("CheckTrigger");
            entityCollider.enabled = true;
        }

        else
        {
            entityCollider.enabled = false;
        }
    }

    public void GetData(GameObject data)
    {
        if (data)
        {
            storedData = data.GetComponent<CircularIndicator>();
        }

        else
        {

        }
    }

    public void BlowUp()
    {
        Collider2D[] hitColliders = Physics2D.OverlapCircleAll(transform.position, 3f);
        foreach (Collider2D collider in hitColliders)
        {
            CollateralScript collateralTrigger = collider.GetComponent<CollateralScript>();
            if (collateralTrigger != null)
            {
                collateralTrigger.CollateralDamage(100f);
            }
        }
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject != null && collision.gameObject.CompareTag("Player"))
        {
            if (gameObject != null)
            {
                Debug.Log("Strike");
                GameObject bomb = Instantiate(explosionVFX, collision.transform.position, Quaternion.identity);

                PlayerHealthScript playerHealth = collision.gameObject.GetComponent<PlayerHealthScript>();
                if (playerHealth != null)
                {
                    playerHealth.TakeDamage(enemyData.attackDamage);
                    Debug.Log("DamagePlayer");
                    Destroy(gameObject);
                }

                
            }
        }
    }
}